name: Create the site

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Flutter Web Build
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Get pubspec version
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Flutter web environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Flutter config
        run: flutter config --enable-web --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter test
        run: flutter test

      - name: Creating a GitHub Tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{ env.VERSION }}
          github_token: ${{ secrets.commit_secret }}

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          token: ${{ secrets.commit_secret }}

      - name: Flutter build web
        run: flutter build web

      - name: Publishing gh-pages
        run: |
          cd example/build/web
          git init
          git config --global user.email edufolly@gmail.com
          git config --global user.name "Eduardo Folly"
          git status
          git remote add origin https://${{ secrets.commit_secret }}@github.com/edufolly/folly_fields.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Publishing web project ($GITHUB_RUN_NUMBER)."
          git push origin gh-pages -f
