name: Create the site

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Flutter Web Build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Get pubspec version
        run: |
          export VERSION=$(grep 'version:' pubspec.yaml | cut -c 10- | cut -f 1 -d '+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Flutter web environment
        uses: subosito/flutter-action@v2

      - name: Flutter config
        run: flutter config --enable-web --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter test
        run: flutter test

      - name: Creating a GitHub Tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Flutter build web
        run: |
          flutter build web \
            --base-href /polygon_background/ \
            --dart-define FLUTTER_WEB_CANVASKIT_URL=/polygon_background/canvaskit/

      - name: Publishing gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build/web
          github_token: ${{ secrets.GITHUB_TOKEN }}
